# -*- coding: utf-8 -*-
"""TSNE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHFsjyJA4mTc4EV0tiUHfW2E6uByTYEE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans

from collections import Counter
from wordcloud import WordCloud

import re

df = pd.read_csv('twitter_dataset.csv')

print(df.head())
print(df.columns)

def clean_tweet(text):

    text = str(text).lower()

    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.split()

    return ' '.join(words)

df['clean_text'] = df['Text'].apply(clean_tweet)

print(df[['Text', 'clean_text']].head())

vectorizer = TfidfVectorizer(max_features=2000)

X = vectorizer.fit_transform(df['clean_text'])

print(X.shape)

kmeans = KMeans(
    n_clusters=5,
    random_state=42
)

df['cluster'] = kmeans.fit_predict(X)

print(df['cluster'].value_counts())

sample_size = min(2000, len(df))

sample_df = df.sample(
    n=sample_size,
    random_state=42
)

X_sample = vectorizer.transform(
    sample_df['clean_text']
)

tsne = TSNE(
    n_components=2,
    perplexity=30,
    learning_rate=200,
    random_state=42
)

X_tsne = tsne.fit_transform(
    X_sample.toarray()
)

print(X_tsne.shape)

sample_df['x'] = X_tsne[:, 0]
sample_df['y'] = X_tsne[:, 1]

print(sample_df.head())

plt.figure(figsize=(12,8))

sns.scatterplot(
    x=sample_df['x'],
    y=sample_df['y'],
    hue=sample_df['cluster'],
    palette='viridis',
    s=80
)

plt.title('t-SNE Visualization of Twitter Dataset')

plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')

plt.show()

plt.figure(figsize=(15,10))

sns.scatterplot(
    x=sample_df['x'],
    y=sample_df['y'],
    hue=sample_df['cluster'],
    palette='deep',
    s=100
)

for i in range(min(50, len(sample_df))):

    plt.text(
        sample_df['x'].iloc[i],
        sample_df['y'].iloc[i],
        sample_df['Username'].iloc[i],
        fontsize=8
    )

plt.title('Twitter Tweet Clusters')

plt.show()

plt.figure(figsize=(10,6))

sns.histplot(
    df['Likes'],
    bins=30,
    kde=True
)

plt.title('Likes Distribution')

plt.xlabel('Likes')

plt.show()

plt.figure(figsize=(10,6))

sns.histplot(
    df['Retweets'],
    bins=30,
    kde=True
)

plt.title('Retweet Distribution')

plt.xlabel('Retweets')

plt.show()

top_users = df['Username'].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=top_users.index,
    y=top_users.values
)

plt.xticks(rotation=45)

plt.title('Top Active Twitter Users')

plt.xlabel('Username')
plt.ylabel('Tweet Count')

plt.show()

cluster_counts = df['cluster'].value_counts()

plt.figure(figsize=(8,6))

plt.pie(
    cluster_counts,
    labels=cluster_counts.index,
    autopct='%1.1f%%'
)

plt.title('Cluster Distribution')

plt.show()

all_words = ' '.join(df['clean_text'])

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='white'
).generate(all_words)

plt.figure(figsize=(15,7))

plt.imshow(wordcloud)

plt.axis('off')

plt.title('Word Cloud of Tweets')

plt.show()

top_words = Counter(all_words.split()).most_common(15)

words = [i[0] for i in top_words]
counts = [i[1] for i in top_words]

plt.figure(figsize=(12,6))

sns.barplot(
    x=words,
    y=counts
)

plt.xticks(rotation=45)

plt.title('Top 15 Frequent Words')

plt.xlabel('Words')
plt.ylabel('Frequency')

plt.show()

df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df['Month'] = df['Timestamp'].dt.month

monthly_tweets = df['Month'].value_counts().sort_index()

plt.figure(figsize=(12,6))

sns.lineplot(
    x=monthly_tweets.index,
    y=monthly_tweets.values,
    marker='o'
)

plt.title('Monthly Tweet Activity')

plt.xlabel('Month')
plt.ylabel('Number of Tweets')

plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    x=df['cluster'],
    y=df['Likes']
)

plt.title('Likes by Cluster')

plt.xlabel('Cluster')
plt.ylabel('Likes')

plt.show()

sample_df.to_csv(
    'twitter_tsne_output.csv',
    index=False
)

print("Output Saved Successfully")